### ISSUE TITLE
Incompatible 1.19.2

### ISSUE THREAD

**Issue by Kirishim-arashi** [burneikis/No-Enchantment-Conflicts#2]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'No Enchantment Conflicts' (noeconflicts) 1.4.1 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'No Enchantment Conflicts' (noeconflicts) 1.4.1 requires any version between 1.19.3 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.5.39 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.5.39 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.5.39 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.5.39 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.5.39 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.14.4' (masa_gadget_mod-1_14_4) 3.0.0-beta+1bf6939 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.15.2' (masa_gadget_mod-1_15_2) 3.0.0-beta+1bf6939 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.16.5' (masa_gadget_mod-1_16_5) 3.0.0-beta+1bf6939 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.17.1' (masa_gadget_mod-1_17_1) 3.0.0-beta+1bf6939 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Masa Gadget for 1.18.2' (masa_gadget_mod-1_18_2) 3.0.0-beta+1bf6939 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.14.4' (ommc-1_14_4) 0.5-beta+8215759 requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.15.2' (ommc-1_15_2) 0.5-beta+8215759 requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.16.5' (ommc-1_16_5) 0.5-beta+8215759 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.17.1' (ommc-1_17_1) 0.5-beta+8215759 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Oh My Minecraft Client for 1.18.2' (ommc-1_18_2) 0.5-beta+8215759 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Tweak My Client for 1.14.4' (tweakmyclient-1_14_4) 3.2.268+fc2ad10-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Tweak My Client for 1.15.2' (tweakmyclient-1_15_2) 3.2.268+fc2ad10-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Tweak My Client for 1.16.5' (tweakmyclient-1_16_5) 3.2.268+fc2ad10-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Tweak My Client for 1.17.1' (tweakmyclient-1_17_1) 3.2.268+fc2ad10-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Tweak My Client for 1.18.2' (tweakmyclient-1_18_2) 3.2.268+fc2ad10-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
[minecraft-exported-crash-info-2023-04-18T19-19-40.zip](https://github.com/AlexBurneikis/No-Enchantment-Conflicts/files/11261087/minecraft-exported-crash-info-2023-04-18T19-19-40.zip)
[minecraft-exported-logs-2023-04-18T19-19-50.log](https://github.com/AlexBurneikis/No-Enchantment-Conflicts/files/11261089/minecraft-exported-logs-2023-04-18T19-19-50.log)

	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![image](https://user-images.githubusercontent.com/84281477/232761443-65002e93-813e-4b4a-a31a-6d25c0aeb31b.png)

**Comment by Kirishim-arashi** [comment]
fix:change jar file fabric.mod.json "depands":{minecraft:1.19,x}

**Comment by burneikis** [comment]
fixed in 38bf4e1
