### ISSUE TITLE
[Suggestion/New Feature/Request]

### ISSUE THREAD

**Issue by Kirishim-arashi** [burneikis/No-Enchantment-Conflicts#3]
[Suggestion/New Feature/Request]
I hope we can do this in survival (actually it is possible in creative)
![image](https://user-images.githubusercontent.com/84281477/233312552-8778ac86-a21b-435a-bf14-576734a43a56.png)

**Comment by Kirishim-arashi** [comment]
You can do it without commands by creative_mode in vanilla minecraft , i hope it can used in survival . thanks

**Comment by burneikis** [comment]
Does the trident work with these enchantments? (Without the mod)

**Comment by Kirishim-arashi** [comment]
Yes, it is work in vanilla

**Comment by Kirishim-arashi** [comment]
i missed one:Fire Aspect & repel [In fact, everything that can be used for a sword can be used for a trident Or even other things]

**Comment by Kirishim-arashi** [comment]
thanks

**Comment by SteveSimonFog** [comment]
Yeah, sure

Burneikis ***@***.***> 于 2023年4月20日周四 下午5:13写道：

**Comment by SteveSimonFog** [comment]
I tried it and it works

**Comment by Kirishim-arashi** [comment]
My friend did this 
[noenchantmentconflicts-1.4.2.zip](https://github.com/AlexBurneikis/No-Enchantment-Conflicts/files/11306127/noenchantmentconflicts-1.4.2.zip)
