### ISSUE TITLE
[Suggestion/New Feature/Request]

### ISSUE THREAD

**Issue by Kirishim-arashi** [burneikis/No-Enchantment-Conflicts#4]
i hope we can use feather_falling in all type of armor in survival_mode[You can do it without commands by creative_mode in vanilla minecraft]
![image](https://user-images.githubusercontent.com/84281477/233829955-bdd7bae2-87dd-42ab-a3e5-4a36a187998a.png)
![image](https://user-images.githubusercontent.com/84281477/233829964-5dceb428-af96-4c45-acc7-cc5c722e71a7.png)
![image](https://user-images.githubusercontent.com/84281477/233829968-dee53a37-40f3-4d13-94c7-2eac95ecf872.png)
also it is work in all type armor

**Comment by SteveSimonFog** [comment]
``
